# Generated by Django 5.2.11 on 2026-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="заголовок")),
                ("content", models.TextField(blank=True, verbose_name="содержимое")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/", verbose_name="превью"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="признак публикации"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="количество просмотров"),
                ),
            ],
            options={
                "verbose_name": "блоговая запись",
                "verbose_name_plural": "блоговые записи",
            },
        ),
    ]
