# Generated by Django 5.2.11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_add_contact"),
    ]

    operations = [
        migrations.DeleteModel(name="Contact"),
    ]
