# Generated by Django 5.2.11 on 2026-03-29 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_contact_again"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="показывать в каталоге"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(10000)],
                verbose_name="сообщение",
            ),
        ),
    ]
